### ISSUE TITLE
Add Mongoose Models for the required Collections

### ISSUE THREAD

**Issue by probablyArth** [SST-OSS/ScalerKeep#1]
## Using the following documents for reference, create mongoose models for the required collections.
- [How to create schema and model in mongoose](https://mongoosejs.com/docs/guide.html)
- [DB diagram for ScalerKeep](https://dbdiagram.io/d/ScalerKeep-653b7d93ffbf5169f0936bea)

## Note
We don't have to add the `_id` property in the schema ourselves since that is auto-generated by MongoDB and mongoose.

## Required collections
- [x] [Users](https://github.com/SST-OSS/ScalerKeep/blob/main/server/models/Users.model.js)
- [x] #2
- [x] #3

**Comment by narasimha-1511** [comment]
hey assign me the issue ..

**Comment by probablyArth** [comment]
> hey assign me the issue ..

Which one, #2 or #3

**Comment by narasimha-1511** [comment]
both

**Comment by probablyArth** [comment]
You can only take one at once

**Comment by narasimha-1511** [comment]
ok books
